#[server]
addr = "localhost:8080"
secret = ""

#[client]
poll_interval = 2_000_000_000#2 sec
report_interval = 1_000_000_000#1 sec

#[database]
conn=""

#[in_memory]
dump_file="/tmp/metrics-db.json"
auto_restore=true
backup_interval=3_000_000_000#3 sec